/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'gainLossUSD' : IDL.Float64,
  'asset' : IDL.Text,
  'flagReason' : IDL.Text,
  'date' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'isShortTerm' : IDL.Bool,
  'costBasisUSD' : IDL.Float64,
  'notes' : IDL.Text,
  'assetName' : IDL.Text,
  'txType' : IDL.Text,
  'exchange' : IDL.Text,
  'priceUSD' : IDL.Float64,
  'amount' : IDL.Float64,
  'isFlagged' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'country' : IDL.Text,
  'plan' : IDL.Text,
  'costBasisMethod' : IDL.Text,
  'currency' : IDL.Text,
  'taxYear' : IDL.Nat,
});
export const HarvestCandidate = IDL.Record({
  'currentPrice' : IDL.Float64,
  'asset' : IDL.Text,
  'taxSavings' : IDL.Float64,
  'unrealizedLoss' : IDL.Float64,
  'assetName' : IDL.Text,
  'amount' : IDL.Float64,
});
export const IntegrationConnection = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'connectedAt' : IDL.Int,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'hasApiKey' : IDL.Bool,
});
export const Holding = IDL.Record({
  'unrealizedGainLoss' : IDL.Float64,
  'asset' : IDL.Text,
  'costBasisUSD' : IDL.Float64,
  'currentPriceUSD' : IDL.Float64,
  'assetName' : IDL.Text,
  'unrealizedPct' : IDL.Float64,
  'currentValueUSD' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const PortfolioSummary = IDL.Record({
  'totalValue' : IDL.Float64,
  'holdings' : IDL.Vec(Holding),
  'totalUnrealizedGain' : IDL.Float64,
});
export const TaxSummary = IDL.Record({
  'estimatedTax' : IDL.Float64,
  'losses' : IDL.Float64,
  'netGains' : IDL.Float64,
  'income' : IDL.Float64,
  'longTermGains' : IDL.Float64,
  'shortTermGains' : IDL.Float64,
  'taxYear' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTransaction' : IDL.Func([Transaction], [IDL.Nat], []),
  'addTransactions' : IDL.Func([IDL.Vec(Transaction)], [IDL.Vec(IDL.Nat)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllTransactions' : IDL.Func([], [], []),
  'deleteIntegration' : IDL.Func([IDL.Text], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'deleteTransactionsByYear' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHarvestCandidates' : IDL.Func([], [IDL.Vec(HarvestCandidate)], ['query']),
  'getIntegrations' : IDL.Func([], [IDL.Vec(IntegrationConnection)], ['query']),
  'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
  'getTaxSummary' : IDL.Func([IDL.Nat], [TaxSummary], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveIntegration' : IDL.Func([IntegrationConnection], [], []),
  'updateTransaction' : IDL.Func([Transaction], [], []),
  'upgradePlan' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'gainLossUSD' : IDL.Float64,
    'asset' : IDL.Text,
    'flagReason' : IDL.Text,
    'date' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'isShortTerm' : IDL.Bool,
    'costBasisUSD' : IDL.Float64,
    'notes' : IDL.Text,
    'assetName' : IDL.Text,
    'txType' : IDL.Text,
    'exchange' : IDL.Text,
    'priceUSD' : IDL.Float64,
    'amount' : IDL.Float64,
    'isFlagged' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'country' : IDL.Text,
    'plan' : IDL.Text,
    'costBasisMethod' : IDL.Text,
    'currency' : IDL.Text,
    'taxYear' : IDL.Nat,
  });
  const HarvestCandidate = IDL.Record({
    'currentPrice' : IDL.Float64,
    'asset' : IDL.Text,
    'taxSavings' : IDL.Float64,
    'unrealizedLoss' : IDL.Float64,
    'assetName' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const IntegrationConnection = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'connectedAt' : IDL.Int,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'hasApiKey' : IDL.Bool,
  });
  const Holding = IDL.Record({
    'unrealizedGainLoss' : IDL.Float64,
    'asset' : IDL.Text,
    'costBasisUSD' : IDL.Float64,
    'currentPriceUSD' : IDL.Float64,
    'assetName' : IDL.Text,
    'unrealizedPct' : IDL.Float64,
    'currentValueUSD' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const PortfolioSummary = IDL.Record({
    'totalValue' : IDL.Float64,
    'holdings' : IDL.Vec(Holding),
    'totalUnrealizedGain' : IDL.Float64,
  });
  const TaxSummary = IDL.Record({
    'estimatedTax' : IDL.Float64,
    'losses' : IDL.Float64,
    'netGains' : IDL.Float64,
    'income' : IDL.Float64,
    'longTermGains' : IDL.Float64,
    'shortTermGains' : IDL.Float64,
    'taxYear' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTransaction' : IDL.Func([Transaction], [IDL.Nat], []),
    'addTransactions' : IDL.Func(
        [IDL.Vec(Transaction)],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllTransactions' : IDL.Func([], [], []),
    'deleteIntegration' : IDL.Func([IDL.Text], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'deleteTransactionsByYear' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHarvestCandidates' : IDL.Func(
        [],
        [IDL.Vec(HarvestCandidate)],
        ['query'],
      ),
    'getIntegrations' : IDL.Func(
        [],
        [IDL.Vec(IntegrationConnection)],
        ['query'],
      ),
    'getPortfolioSummary' : IDL.Func([], [PortfolioSummary], ['query']),
    'getTaxSummary' : IDL.Func([IDL.Nat], [TaxSummary], ['query']),
    'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveIntegration' : IDL.Func([IntegrationConnection], [], []),
    'updateTransaction' : IDL.Func([Transaction], [], []),
    'upgradePlan' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };